packages:
  - 'packages/*'
  - 'website'

onlyBuiltDependencies:
  - '@deepseek-ai/dsh-subprocess-local'
  - esbuild

ignoredBuiltDependencies:
  - '@google/genai'
  - koffi
  - node-pty
  - protobufjs