// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	showPopup: (mode: string | null) => typedError<null, string>(__TAURI_INVOKE("show_popup", { mode })),
	hidePopup: () => typedError<null, string>(__TAURI_INVOKE("hide_popup")),
	settingsGet: (key: string) => typedError<"Null" | boolean | number | null | string | SettingsValue[] | ([string, SettingsValue])[] | null, string>(__TAURI_INVOKE("settings_get", { key })),
	settingsSet: (key: string, value: SettingsValue) => typedError<null, string>(__TAURI_INVOKE("settings_set", { key, value })),
	getSelectedText: () => __TAURI_INVOKE<string>("get_selected_text"),
};

/* Types */
/**
 *  settings.json 里的值：JSON 语义的封闭子集（形状与 `serde_json::Value` 同构）。
 * 
 *  用 `#[derive(Type)]` 生成 specta 类型：derive 内部按 TypeId 缓存递归定义，
 *  因此自递归安全；不能用 `serde_json::Value` 直接进命令签名 —— specta 对它的
 *  legacy 实现是 `inline` 非缓存自递归，导致 bindings 导出时栈溢出。
 */
export type SettingsValue = "Null" | boolean | number | null | string | SettingsValue[] | ([string, SettingsValue])[];

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

