// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	showPopup: (mode: string | null) => typedError<null, string>(__TAURI_INVOKE("show_popup", { mode })),
	hidePopup: () => typedError<null, string>(__TAURI_INVOKE("hide_popup")),
	settingsGet: (key: string) => typedError<"Null" | boolean | number | null | string | SettingsValue[] | ([string, SettingsValue])[] | null, string>(__TAURI_INVOKE("settings_get", { key })),
	settingsSet: (key: string, value: SettingsValue) => typedError<null, string>(__TAURI_INVOKE("settings_set", { key, value })),
	getSelectedText: () => __TAURI_INVOKE<SelectedText>("get_selected_text"),
	translate: (request: TranslateRequest_Deserialize) => typedError<TranslateResult, EngineErrorPayload>(__TAURI_INVOKE("translate", { request })),
	providersSnapshot: () => typedError<ProvidersSnapshot, string>(__TAURI_INVOKE("providers_snapshot")),
	providersSave: (config: ProvidersConfig_Deserialize) => typedError<ProvidersSnapshot, string>(__TAURI_INVOKE("providers_save", { config })),
	providerSaveApiKey: (provider: string, apiKey: string) => typedError<ProvidersSnapshot, string>(__TAURI_INVOKE("provider_save_api_key", { provider, apiKey })),
	providerTest: (provider: string) => typedError<TestProviderResult, string>(__TAURI_INVOKE("provider_test", { provider })),
	historyList: () => typedError<HistoryEntry[], string>(__TAURI_INVOKE("history_list")),
	historyClear: () => typedError<number, string>(__TAURI_INVOKE("history_clear")),
	hotkeysSnapshot: () => __TAURI_INVOKE<HotkeysSnapshot>("hotkeys_snapshot"),
	hotkeysSet: (id: HotkeyId, accelerator: string) => typedError<HotkeysSnapshot, string>(__TAURI_INVOKE("hotkeys_set", { id, accelerator })),
	hotkeysReset: () => typedError<HotkeysSnapshot, string>(__TAURI_INVOKE("hotkeys_reset")),
	hotkeysSuspend: () => __TAURI_INVOKE<void>("hotkeys_suspend"),
	hotkeysResume: () => __TAURI_INVOKE<void>("hotkeys_resume"),
	accessibilityStatus: () => __TAURI_INVOKE<AccessibilityStatus>("accessibility_status"),
	openAccessibilitySettings: () => typedError<boolean, string>(__TAURI_INVOKE("open_accessibility_settings")),
	permissionsSnapshot: () => __TAURI_INVOKE<PermissionsSnapshot>("permissions_snapshot"),
	requestPermission: (id: string) => typedError<boolean, string>(__TAURI_INVOKE("request_permission", { id })),
	openPermissionSettings: (id: string) => typedError<boolean, string>(__TAURI_INVOKE("open_permission_settings", { id })),
	completeOnboarding: () => typedError<PermissionsSnapshot, string>(__TAURI_INVOKE("complete_onboarding")),
	restartApp: () => __TAURI_INVOKE<void>("restart_app"),
};

/** Events */
export const events = {
	captureChanged: makeEvent<CaptureChangedEvent>("capture://changed"),
	engineError: makeEvent<EngineErrorEvent>("engine://error"),
	hotkeyPressed: makeEvent<HotkeyPressedEvent>("hotkey://pressed"),
};

/* Types */
/**  旧设置页状态卡形状，由 permissions snapshot 投影而来。 */
export type AccessibilityStatus = {
	trusted: boolean,
	platform: string,
	hint: string | null,
};

/**  剪贴板兜底稍后完成时补发（AX/UIA 为空才走）。 */
export type CaptureChangedEvent = SelectedText;

/**  specta 单源事件契约；Tauri 侧实际事件名保持 `engine://error`（§3.5）。 */
export type EngineErrorEvent = EngineErrorPayload;

/**  可复制、可展示的错误负载。这也是 `engine://error` 事件的 payload。 */
export type EngineErrorPayload = {
	provider: string,
	code: string,
	message: string,
	hint: string | null,
	copyable: string,
};

export type HistoryEntry = {
	id: number,
	createdAt: string,
	kind: string,
	input: string,
	output: string,
	engine: string,
	fromLang: string | null,
	toLang: string | null,
	durationMs: number,
	sourceApp: string | null,
	meta: string | null,
};

export type HotkeyBinding = {
	id: HotkeyId,
	title: string,
	accelerator: string,
	display: string,
	isDefault: boolean,
	registered: boolean,
};

export type HotkeyId = "translate" | "grammar" | "panel";

/**  热键载荷：模式 + 显示前读到的选中文本（§3.4）。 */
export type HotkeyPressedEvent = {
	mode: string,
	selection: SelectedText,
};

export type HotkeysSnapshot = {
	platform: string,
	bindings: HotkeyBinding[],
};

export type PermissionItem = {
	id: string,
	title: string,
	description: string,
	granted: boolean,
	required: boolean,
	hint: string | null,
};

export type PermissionsSnapshot = {
	platform: string,
	items: PermissionItem[],
	allRequiredGranted: boolean,
	onboardingSeen: boolean,
	needsOnboarding: boolean,
};

/**  非密钥的 Provider 配置（settings.json，§6.2：密钥在 keyring 里）。 */
export type ProviderConfig = ProviderConfig_Serialize | ProviderConfig_Deserialize;

/**  非密钥的 Provider 配置（settings.json，§6.2：密钥在 keyring 里）。 */
export type ProviderConfig_Deserialize = {
	enabled?: boolean,
	baseUrl?: string | null,
	model?: string | null,
	kind?: string | null,
	temperature?: number | null,
	maxTokens?: number | null,
	formality?: string | null,
};

/**  非密钥的 Provider 配置（settings.json，§6.2：密钥在 keyring 里）。 */
export type ProviderConfig_Serialize = {
	enabled: boolean,
	baseUrl?: string | null,
	model?: string | null,
	kind?: string | null,
	temperature?: number | null,
	maxTokens?: number | null,
	formality?: string | null,
};

/**  WebView 可见的 Provider 状态（D2：任何时候都不含密钥明文）。 */
export type ProviderView = {
	id: string,
	label: string,
	enabled: boolean,
	hasKey: boolean,
	kind: string | null,
	baseUrl: string | null,
	model: string | null,
	temperature: number | null,
	maxTokens: number | null,
	formality: string | null,
	testable: boolean,
};

/**  settings.json → `providers` 键的整体形状（§5.1 精简到 M1 需要的字段）。 */
export type ProvidersConfig = ProvidersConfig_Serialize | ProvidersConfig_Deserialize;

/**  settings.json → `providers` 键的整体形状（§5.1 精简到 M1 需要的字段）。 */
export type ProvidersConfig_Deserialize = {
	deepl?: ProviderConfig_Deserialize,
	llm?: ProviderConfig_Deserialize,
	youdao?: ProviderConfig_Deserialize,
	defaultTranslate?: string,
	writeHistory?: boolean,
};

/**  settings.json → `providers` 键的整体形状（§5.1 精简到 M1 需要的字段）。 */
export type ProvidersConfig_Serialize = {
	deepl: ProviderConfig_Serialize,
	llm: ProviderConfig_Serialize,
	youdao: ProviderConfig_Serialize,
	defaultTranslate: string,
	writeHistory: boolean,
};

/**  设置页一次拉取的非密钥配置快照。 */
export type ProvidersSnapshot = {
	defaultTranslate: string,
	writeHistory: boolean,
	providers: ProviderView[],
};

export type SelectedText = {
	text: string,
	method: SelectionMethod,
};

export type SelectionMethod = "ax" | "uia" | "clipboard" | "manual";

/**
 *  settings.json 里的值：JSON 语义的封闭子集（形状与 `serde_json::Value` 同构）。
 * 
 *  用 `#[derive(Type)]` 生成 specta 类型：derive 内部按 TypeId 缓存递归定义，
 *  因此自递归安全；不能用 `serde_json::Value` 直接进命令签名 —— specta 对它的
 *  legacy 实现是 `inline` 非缓存自递归，导致 bindings 导出时栈溢出。
 */
export type SettingsValue = "Null" | boolean | number | null | string | SettingsValue[] | ([string, SettingsValue])[];

export type TestProviderResult = {
	ok: boolean,
	reason: string | null,
};

/**  翻译请求：§5.2 统一进出参 `{text, from?, to}`。 */
export type TranslateRequest = TranslateRequest_Serialize | TranslateRequest_Deserialize;

/**  翻译请求：§5.2 统一进出参 `{text, from?, to}`。 */
export type TranslateRequest_Deserialize = {
	text: string,
	from?: string | null,
	to: string,
};

/**  翻译请求：§5.2 统一进出参 `{text, from?, to}`。 */
export type TranslateRequest_Serialize = {
	text: string,
	from?: string | null,
	to: string,
};

/**  翻译结果：§5.4 标准化 Schema。 */
export type TranslateResult = {
	engine: string,
	output: string,
	input: string,
	detectedFrom: string | null,
	target: string,
	durationMs: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

